FROM python:3.11-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends ffmpeg espeak-ng && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.coqui.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY worker.py .
ENV ENABLE_COQUI=1
CMD ["python", "worker.py"]
