import { uid } from '../store/project.js';
import type { SceneObject, Clip } from '@manim/codegen';

export type TemplateCategory =
  | 'general'
  | 'calculus'
  | 'linear_algebra'
  | 'trigonometry'
  | 'statistics'
  | 'programming';

/** A wider clip type that allows extra template-only fields (overshoot, morphQuality, …). */
type TemplateClip = Clip & Record<string, unknown>;

/** A minimal project snapshot used by template factories. */
export interface TemplateProject {
  name: string;
  editorMode: string;
  codeSource: string;
  stage: Record<string, unknown>;
  assets: unknown[];
  groups: unknown[];
  sceneDuration: number;
  objects: SceneObject[];
  tracks: Array<{ id: string; name?: string; clips: TemplateClip[] }>;
}

/** A single entry in the template palette. */
export interface Template {
  id: string;
  label: string;
  description: string;
  icon: string;
  category: TemplateCategory;
  project: (() => TemplateProject) | null;
}

const STAGE = {
  width: 1920,
  height: 1080,
  backgroundColor: '#0f0f0f',
  backgroundOpacity: 1,
  backgroundImage: null,
  gridVisible: true,
  gridSize: 8,
  gridColor: '#ffffff',
  gridOpacity: 0.12,
  snapEnabled: true,
  snapToGrid: true,
  snapToCenter: true,
  snapToObjects: false,
};

export const TEMPLATES: Template[] = [
  {
    id: 'blank',
    label: 'Blank Project',
    description: 'Start from scratch',
    icon: '□',
    category: 'general',
    project: null,
  },
  {
    id: 'formula_reveal',
    label: 'Formula Reveal',
    description: 'Reveal a LaTeX formula with a writing effect',
    icon: '∑',
    category: 'general',
    project: () => {
      const id1 = uid('obj');
      return {
        name: 'Formula Reveal',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 6,
        objects: [
          {
            id: id1,
            type: 'latex',
            name: 'Formula',
            x: 960,
            y: 540,
            width: 300,
            height: 100,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 0,
            latex: 'E = mc^2',
            enterTime: 0,
            duration: 5,
            enterAnim: 'write',
            exitAnim: 'none',
            enterAnimDur: 1.5,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'shape_transform',
    label: 'Shape Transform',
    description: 'Morph one shape into another',
    icon: '⇌',
    category: 'general',
    project: () => {
      const src = uid('obj');
      const tgt = uid('obj');
      const clip = uid('clip');
      return {
        name: 'Shape Transform',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 6,
        objects: [
          {
            id: src,
            type: 'circle',
            name: 'Source',
            x: 960,
            y: 540,
            width: 200,
            height: 200,
            rotation: 0,
            fill: '#3b82f6',
            stroke: '#ffffff',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 0,
            enterTime: 0,
            duration: 4,
            enterAnim: 'grow_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
          {
            id: tgt,
            type: 'square',
            name: 'Target',
            x: 960,
            y: 540,
            width: 200,
            height: 200,
            rotation: 0,
            fill: '#22c55e',
            stroke: '#ffffff',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 1,
            enterTime: 1.5,
            duration: 4,
            enterAnim: 'none',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [
          {
            id: 'track_1',
            name: 'Track 1',
            clips: [
              {
                id: clip,
                type: 'transform',
                startTime: 1.5,
                duration: 1.5,
                easing: 'ease_in_out_cubic',
                sourceId: src,
                targetId: tgt,
                params: {},
                overshoot: 0,
                settle: 1.0,
                morphQuality: 'medium',
              },
            ],
          },
          { id: 'track_2', name: 'Track 2', clips: [] },
        ],
      };
    },
  },
  {
    id: 'title_slide',
    label: 'Title Slide',
    description: 'Title and subtitle fade in sequentially',
    icon: 'T',
    category: 'general',
    project: () => {
      const title = uid('obj');
      const sub = uid('obj');
      return {
        name: 'Title Slide',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 8,
        objects: [
          {
            id: title,
            type: 'text',
            name: 'Title',
            x: 960,
            y: 480,
            width: 800,
            height: 80,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 0,
            content: 'Title Text',
            fontSize: 72,
            fontFamily: 'Roboto',
            textAlign: 'center',
            fontWeight: 'bold',
            fontStyle: 'normal',
            enterTime: 0,
            duration: 7,
            enterAnim: 'fly_in_bottom',
            exitAnim: 'none',
            enterAnimDur: 0.6,
            exitAnimDur: 0.5,
          },
          {
            id: sub,
            type: 'text',
            name: 'Subtitle',
            x: 960,
            y: 600,
            width: 600,
            height: 50,
            rotation: 0,
            fill: '#94a3b8',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 1,
            content: 'Subtitle description',
            fontSize: 36,
            fontFamily: 'Roboto',
            textAlign: 'center',
            fontWeight: 'normal',
            fontStyle: 'normal',
            enterTime: 0.5,
            duration: 6.5,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.8,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'axes_intro',
    label: 'Coordinate System',
    description: 'Axes are drawn onto the stage',
    icon: '⊕',
    category: 'general',
    project: () => {
      const ax = uid('obj');
      const lbl = uid('obj');
      return {
        name: 'Coordinate System',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 6,
        objects: [
          {
            id: ax,
            type: 'axes',
            name: 'Axes',
            x: 960,
            y: 540,
            width: 800,
            height: 500,
            rotation: 0,
            fill: '#ffffff',
            stroke: '#ffffff',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 0,
            // The label promises f(x) = x², so the axes plot it (y up to 9).
            xRange: [-3, 3, 1],
            yRange: [-1, 9, 1],
            graphs: [
              {
                id: uid('obj'),
                expression: 'x**2',
                color: '#3b82f6',
                xMin: -3,
                xMax: 3,
              },
            ],
            enterTime: 0,
            duration: 5,
            enterAnim: 'draw',
            exitAnim: 'none',
            enterAnimDur: 1.2,
            exitAnimDur: 0.5,
          },
          {
            id: lbl,
            // A LaTeX (MathTex) object so the expression typesets in the proper
            // math font (italic x, real superscript) instead of a plain Text font.
            type: 'latex',
            name: 'Label',
            x: 960,
            y: 200,
            width: 220,
            height: 80,
            rotation: 0,
            fill: '#94a3b8',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 1,
            latex: 'f(x) = x^2',
            enterTime: 1.5,
            duration: 3.5,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'limit_approach',
    label: 'Limit Approach',
    description: 'Visualize the limit concept as x approaches c',
    icon: 'lim',
    category: 'calculus',
    project: () => {
      const np = uid('obj');
      const d1 = uid('obj');
      const d2 = uid('obj');
      const lbl = uid('obj');
      return {
        name: 'Limit Approach',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 6,
        objects: [
          {
            id: np,
            type: 'numberplane',
            name: 'Plane',
            x: 960,
            y: 540,
            width: 1000,
            height: 620,
            rotation: 0,
            fill: '#1e293b',
            stroke: '#334155',
            strokeWidth: 1,
            opacity: 1,
            zOrder: 0,
            xRange: [-5, 5, 1],
            yRange: [-3, 3, 1],
            enterTime: 0,
            duration: 5,
            enterAnim: 'draw',
            exitAnim: 'none',
            enterAnimDur: 1.0,
            exitAnimDur: 0.5,
          },
          {
            id: d1,
            type: 'dot',
            name: 'Point approaching x',
            x: 800,
            y: 540,
            width: 20,
            height: 20,
            rotation: 0,
            fill: '#ef4444',
            stroke: '#ef4444',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 2,
            enterTime: 1.2,
            duration: 4.8,
            enterAnim: 'grow_in',
            exitAnim: 'none',
            enterAnimDur: 0.3,
            exitAnimDur: 0.5,
          },
          {
            id: d2,
            type: 'dot',
            name: 'Limit point',
            x: 960,
            y: 540,
            width: 24,
            height: 24,
            rotation: 0,
            fill: '#f97316',
            stroke: '#f97316',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 3,
            enterTime: 2.0,
            duration: 4,
            enterAnim: 'grow_in',
            exitAnim: 'none',
            enterAnimDur: 0.4,
            exitAnimDur: 0.5,
          },
          {
            id: lbl,
            type: 'latex',
            name: 'Limit',
            x: 960,
            y: 160,
            width: 480,
            height: 80,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 4,
            latex: '\\lim_{x \\to 0} f(x) = L',
            enterTime: 1.5,
            duration: 4.5,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'derivative_tangent',
    label: 'Derivative Tangent',
    description: 'Show the derivative and tangent line at a point',
    icon: '∂',
    category: 'calculus',
    project: () => {
      const ax = uid('obj');
      const lbl = uid('obj');
      const gid = uid('obj');
      return {
        name: 'Derivative Tangent',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 8,
        objects: [
          {
            id: ax,
            type: 'axes',
            name: 'Axes',
            x: 960,
            y: 560,
            width: 900,
            height: 560,
            rotation: 0,
            fill: '#ffffff',
            stroke: '#ffffff',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 0,
            xRange: [-3, 3, 1],
            yRange: [-1, 5, 1],
            graphs: [
              {
                id: gid,
                expression: 'x**2',
                color: '#3b82f6',
                xMin: -2.2, // x² ≤ 4.84 stays under yRange's 5
                xMax: 2.2,
                strokeWidth: 3,
                tangent: { enabled: true, x: 1 },
              },
            ],
            enterTime: 0,
            duration: 7,
            enterAnim: 'draw',
            exitAnim: 'none',
            enterAnimDur: 1.5,
            exitAnimDur: 0.5,
          },
          {
            id: lbl,
            type: 'latex',
            name: 'Derivative',
            x: 960,
            y: 160,
            width: 500,
            height: 80,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 1,
            latex: "f'(x) = 2x,\\quad f'(1) = 2",
            enterTime: 2.0,
            duration: 6.0,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'integral_area',
    label: 'Integral Area',
    description: 'Show a definite integral and Riemann area',
    icon: '∫',
    category: 'calculus',
    project: () => {
      const ax = uid('obj');
      const lbl = uid('obj');
      const gid = uid('obj');
      return {
        name: 'Integral Area',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 7,
        objects: [
          {
            id: ax,
            type: 'axes',
            name: 'Axes',
            x: 960,
            y: 570,
            width: 900,
            height: 560,
            rotation: 0,
            fill: '#ffffff',
            stroke: '#ffffff',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 0,
            xRange: [0, 4, 1],
            // x² reaches 9 at x = 3 (the integral's upper limit): keep it on the axes.
            yRange: [0, 10, 2],
            graphs: [
              {
                id: gid,
                expression: 'x**2',
                color: '#3b82f6',
                xMin: 0,
                xMax: 3,
                strokeWidth: 3,
                area: { enabled: true, xMin: 0, xMax: 3, color: '#3b82f6', opacity: 0.3 },
                riemann: {
                  enabled: true,
                  xMin: 0,
                  xMax: 3,
                  dx: 0.5,
                  type: 'right',
                  color: '#22c55e',
                },
              },
            ],
            enterTime: 0,
            duration: 6,
            enterAnim: 'draw',
            exitAnim: 'none',
            enterAnimDur: 1.5,
            exitAnimDur: 0.5,
          },
          {
            id: lbl,
            type: 'latex',
            name: 'Integral',
            x: 960,
            y: 160,
            width: 440,
            height: 80,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 1,
            latex: '\\int_0^3 x^2\\,dx = 9',
            enterTime: 2.0,
            duration: 5.0,
            enterAnim: 'write',
            exitAnim: 'none',
            enterAnimDur: 1.0,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'vector_addition',
    label: 'Vector Addition',
    description: 'Show the resultant sum of two vectors',
    icon: '→',
    category: 'linear_algebra',
    project: () => {
      const vc1 = uid('obj');
      const vc2 = uid('obj');
      const res = uid('obj');
      const lbl = uid('obj');
      return {
        name: 'Vector Addition',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 7,
        objects: [
          {
            id: vc1,
            type: 'vector_components',
            name: 'u vector',
            x: 660,
            y: 800,
            width: 450,
            height: 300,
            rotation: 0,
            fill: '#3b82f6',
            stroke: '#3b82f6',
            strokeWidth: 3,
            opacity: 1,
            zOrder: 0,
            vx: 450,
            vy: -120,
            enterTime: 0,
            duration: 6,
            enterAnim: 'grow_in',
            exitAnim: 'none',
            enterAnimDur: 0.8,
            exitAnimDur: 0.5,
          },
          {
            id: vc2,
            type: 'vector_components',
            name: 'v vector',
            x: 1110,
            y: 680,
            width: 380,
            height: 250,
            rotation: 0,
            fill: '#a855f7',
            stroke: '#a855f7',
            strokeWidth: 3,
            opacity: 1,
            zOrder: 1,
            vx: 150,
            vy: -380,
            enterTime: 1.0,
            duration: 5,
            enterAnim: 'grow_in',
            exitAnim: 'none',
            enterAnimDur: 0.8,
            exitAnimDur: 0.5,
          },
          {
            id: res,
            type: 'arrow',
            name: 'Resultant',
            // From u's tail (660, 800) to v's tip (1260, 300): centred on the
            // midpoint, rotated up by atan2(500, 600).
            x: 960,
            y: 550,
            width: Math.round(Math.hypot(600, 500) * 10) / 10,
            height: 20,
            rotation: Math.round(((-Math.atan2(500, 600) * 180) / Math.PI) * 100) / 100,
            fill: '#f97316',
            stroke: '#f97316',
            strokeWidth: 4,
            opacity: 1,
            zOrder: 2,
            enterTime: 2.0,
            duration: 4,
            enterAnim: 'grow_arrow',
            exitAnim: 'none',
            enterAnimDur: 0.8,
            exitAnimDur: 0.5,
          },
          {
            id: lbl,
            type: 'latex',
            name: 'Formula',
            x: 960,
            y: 160,
            width: 400,
            height: 80,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 3,
            latex: '\\vec{u} + \\vec{v} = \\vec{w}',
            enterTime: 2.5,
            duration: 4.5,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'matrix_product',
    label: 'Matrix Multiplication',
    description: 'Multiply two 2×2 matrices',
    icon: '⊗',
    category: 'linear_algebra',
    project: () => {
      const mA = uid('obj');
      const mB = uid('obj');
      const mC = uid('obj');
      const lbl = uid('obj');
      return {
        name: 'Matrix Multiplication',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 7,
        objects: [
          {
            id: mA,
            type: 'matrix',
            name: 'A',
            x: 480,
            y: 540,
            width: 200,
            height: 160,
            rotation: 0,
            fill: '#3b82f6',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 0,
            matrixData: [
              ['1', '2'],
              ['3', '4'],
            ],
            bracket: '[',
            enterTime: 0,
            duration: 6,
            enterAnim: 'grow_in',
            exitAnim: 'none',
            enterAnimDur: 0.6,
            exitAnimDur: 0.5,
          },
          {
            id: lbl,
            type: 'latex',
            name: 'Times',
            x: 720,
            y: 540,
            width: 80,
            height: 60,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 1,
            latex: '\\cdot',
            // A fixed size: fit-to-box would blow the tiny glyph up to 80 px.
            fontSize: 72,
            enterTime: 0.7,
            duration: 5.3,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.3,
            exitAnimDur: 0.5,
          },
          {
            id: mB,
            type: 'matrix',
            name: 'B',
            x: 960,
            y: 540,
            width: 200,
            height: 160,
            rotation: 0,
            fill: '#22c55e',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 2,
            matrixData: [
              ['5', '6'],
              ['7', '8'],
            ],
            bracket: '[',
            enterTime: 0.7,
            duration: 5.3,
            enterAnim: 'grow_in',
            exitAnim: 'none',
            enterAnimDur: 0.6,
            exitAnimDur: 0.5,
          },
          {
            id: mC,
            type: 'matrix',
            name: 'Result',
            x: 1380,
            y: 540,
            width: 240,
            height: 160,
            rotation: 0,
            fill: '#f97316',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 3,
            matrixData: [
              ['19', '22'],
              ['43', '50'],
            ],
            bracket: '[',
            enterTime: 2.0,
            duration: 4,
            enterAnim: 'grow_in',
            exitAnim: 'none',
            enterAnimDur: 0.6,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'unit_circle',
    label: 'Unit Circle',
    description: 'Trigonometric unit circle with sin/cos display',
    icon: '○',
    category: 'trigonometry',
    project: () => {
      // One plane unit = U px (2 Manim units), so the circle really is the
      // unit circle and P = (cos θ, sin θ) sits on it. θ = 40°: cos ≠ sin, so
      // the two projections are visibly different.
      const U = 270;
      const CX = 960;
      const CY = 580;
      const TH = (40 * Math.PI) / 180;
      const PX = Math.round(U * Math.cos(TH) * 10) / 10; // 206.8
      const PY = Math.round(U * Math.sin(TH) * 10) / 10; // 173.6
      const END = 10;
      const base = (enterTime: number) => ({
        rotation: 0,
        opacity: 1,
        enterTime,
        duration: END - enterTime,
        exitAnim: 'none',
        exitAnimDur: 0.5,
      });
      return {
        name: 'Unit Circle',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: END,
        objects: [
          {
            ...base(0),
            id: uid('obj'),
            type: 'numberplane',
            name: 'Plane',
            x: CX,
            y: CY,
            width: 4 * U,
            height: 3 * U,
            fill: '#1e293b',
            stroke: '#334155',
            strokeWidth: 1,
            zOrder: 0,
            xRange: [-2, 2, 0.5],
            yRange: [-1.5, 1.5, 0.5],
            xStep: 0.5,
            yStep: 0.5,
            enterAnim: 'draw',
            enterAnimDur: 1.0,
          },
          {
            ...base(0.8),
            id: uid('obj'),
            type: 'circle',
            name: 'Unit Circle',
            x: CX,
            y: CY,
            width: 2 * U,
            height: 2 * U,
            fill: 'transparent',
            stroke: '#e2e8f0',
            strokeWidth: 3,
            zOrder: 1,
            enterAnim: 'draw',
            enterAnimDur: 1.2,
          },
          {
            // Ray 1 runs along the x-axis to (1, 0); ray 2 is the radius OP.
            ...base(2.2),
            id: uid('obj'),
            type: 'angle',
            name: 'Angle θ',
            x: CX,
            y: CY,
            width: U,
            height: U,
            fill: '#facc15',
            stroke: '#facc15',
            strokeWidth: 3,
            zOrder: 2,
            vertex: [0, 0],
            point1: [U, 0],
            point2: [PX, -PY],
            rightAngle: false,
            radius: 0.5,
            label: '\\theta',
            enterAnim: 'draw',
            enterAnimDur: 1.0,
          },
          {
            ...base(3.2),
            id: uid('obj'),
            type: 'dot',
            name: 'P',
            x: CX + PX,
            y: CY - PY,
            width: 22,
            height: 22,
            fill: '#f8fafc',
            stroke: '#f8fafc',
            strokeWidth: 0,
            zOrder: 5,
            enterAnim: 'grow_in',
            enterAnimDur: 0.4,
          },
          {
            ...base(3.5),
            id: uid('obj'),
            type: 'latex',
            name: 'P label',
            x: CX + PX + 150,
            y: CY - PY - 45,
            width: 300,
            height: 50,
            fill: '#f8fafc',
            stroke: 'transparent',
            strokeWidth: 0,
            zOrder: 6,
            latex: 'P = (\\cos\\theta,\\ \\sin\\theta)',
            enterAnim: 'fade_in',
            enterAnimDur: 0.5,
          },
          {
            ...base(4.4),
            id: uid('obj'),
            type: 'line',
            name: 'cos θ',
            x: CX + PX / 2,
            y: CY,
            width: PX,
            height: 0,
            fill: '#38bdf8',
            stroke: '#38bdf8',
            strokeWidth: 6,
            zOrder: 3,
            enterAnim: 'draw',
            enterAnimDur: 0.8,
          },
          {
            ...base(4.9),
            id: uid('obj'),
            type: 'latex',
            name: 'cos label',
            x: CX + PX / 2,
            y: CY + 40,
            width: 110,
            height: 40,
            fill: '#38bdf8',
            stroke: 'transparent',
            strokeWidth: 0,
            zOrder: 6,
            latex: '\\cos\\theta',
            enterAnim: 'fade_in',
            enterAnimDur: 0.5,
          },
          {
            ...base(5.6),
            id: uid('obj'),
            type: 'line',
            name: 'sin θ',
            x: CX + PX,
            y: CY - PY / 2,
            width: PY,
            height: 0,
            rotation: 90,
            fill: '#f87171',
            stroke: '#f87171',
            strokeWidth: 6,
            zOrder: 4,
            enterAnim: 'draw',
            enterAnimDur: 0.8,
          },
          {
            ...base(6.1),
            id: uid('obj'),
            type: 'latex',
            name: 'sin label',
            x: CX + PX + 75,
            y: CY - PY / 2,
            width: 110,
            height: 40,
            fill: '#f87171',
            stroke: 'transparent',
            strokeWidth: 0,
            zOrder: 6,
            latex: '\\sin\\theta',
            enterAnim: 'fade_in',
            enterAnimDur: 0.5,
          },
          {
            ...base(7.0),
            id: uid('obj'),
            type: 'latex',
            name: 'Pythagorean identity',
            x: CX,
            y: 105,
            width: 560,
            height: 70,
            fill: '#f8fafc',
            stroke: 'transparent',
            strokeWidth: 0,
            zOrder: 7,
            latex: '\\cos^2\\theta + \\sin^2\\theta = 1',
            enterAnim: 'write',
            enterAnimDur: 1.2,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'sin_cos_wave',
    label: 'Sine & Cosine Graph',
    description: 'Compare the sine and cosine waves',
    icon: '∿',
    category: 'trigonometry',
    project: () => {
      const ax = uid('obj');
      const g1 = uid('obj');
      const g2 = uid('obj');
      return {
        name: 'Sine & Cosine Graph',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 7,
        objects: [
          {
            id: ax,
            type: 'axes',
            name: 'Axes',
            x: 960,
            y: 560,
            width: 1100,
            height: 500,
            rotation: 0,
            fill: '#ffffff',
            stroke: '#ffffff',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 0,
            xRange: [0, 6.28, 1.57],
            yRange: [-1.5, 1.5, 0.5],
            graphs: [
              {
                id: g1,
                expression: 'sin(x)',
                color: '#3b82f6',
                xMin: 0,
                xMax: 6.28,
                strokeWidth: 3,
              },
              {
                id: g2,
                expression: 'cos(x)',
                color: '#ef4444',
                xMin: 0,
                xMax: 6.28,
                strokeWidth: 3,
              },
            ],
            enterTime: 0,
            duration: 6,
            enterAnim: 'draw',
            exitAnim: 'none',
            enterAnimDur: 2.0,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'normal_distribution',
    label: 'Normal Distribution',
    description: 'Gaussian bell curve with the ±1σ region',
    icon: '⌒',
    category: 'statistics',
    project: () => {
      const ax = uid('obj');
      const g1 = uid('obj');
      const lbl1 = uid('obj');
      const lbl2 = uid('obj');
      return {
        name: 'Normal Distribution',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 6,
        objects: [
          {
            id: ax,
            type: 'axes',
            name: 'Axes',
            x: 960,
            y: 600,
            width: 1200,
            height: 500,
            rotation: 0,
            fill: '#ffffff',
            stroke: '#ffffff',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 0,
            xRange: [-4, 4, 1],
            yRange: [0, 0.5, 0.1],
            graphs: [
              {
                id: g1,
                expression: '2.718**(-(x**2)/2)/2.507',
                color: '#3b82f6',
                xMin: -4,
                xMax: 4,
                strokeWidth: 3,
                area: { enabled: true, xMin: -1, xMax: 1, color: '#3b82f6', opacity: 0.3 },
              },
            ],
            enterTime: 0,
            duration: 5,
            enterAnim: 'draw',
            exitAnim: 'none',
            enterAnimDur: 2.0,
            exitAnimDur: 0.5,
          },
          {
            id: lbl1,
            type: 'latex',
            name: 'Formula',
            x: 960,
            y: 140,
            width: 400,
            height: 80,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 1,
            latex: '\\mathcal{N}(0,1)',
            enterTime: 2.2,
            duration: 3.8,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
          {
            id: lbl2,
            type: 'latex',
            name: '68%',
            x: 960,
            y: 220,
            width: 200,
            height: 60,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 2,
            latex: '68\\%',
            enterTime: 2.8,
            duration: 3.2,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.4,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'theorem_proof',
    label: 'Theorem Proof',
    description: 'Theorem statement, proof steps, and conclusion',
    icon: '∎',
    category: 'general',
    project: () => {
      const thmTxt = uid('obj');
      const proofHdr = uid('obj');
      const proofBody = uid('obj');
      const qed = uid('obj');
      return {
        name: 'Theorem Proof',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 10,
        objects: [
          {
            id: thmTxt,
            type: 'latex',
            name: 'Theorem',
            x: 960,
            y: 260,
            width: 900,
            height: 120,
            rotation: 0,
            fill: '#facc15',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 0,
            latex: 'a^2 + b^2 = c^2',
            enterTime: 0,
            duration: 9,
            enterAnim: 'write',
            exitAnim: 'none',
            enterAnimDur: 1.0,
            exitAnimDur: 0.5,
          },
          {
            id: proofHdr,
            type: 'text',
            name: 'Proof title',
            x: 960,
            y: 440,
            width: 300,
            height: 60,
            rotation: 0,
            fill: '#94a3b8',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 1,
            content: 'Proof:',
            fontSize: 32,
            fontFamily: 'Arial',
            enterTime: 1.5,
            duration: 7.5,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.4,
            exitAnimDur: 0.5,
          },
          {
            id: proofBody,
            type: 'text',
            name: 'Proof text',
            x: 960,
            y: 580,
            width: 1100,
            height: 160,
            rotation: 0,
            fill: '#e2e8f0',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 2,
            content:
              'In a right triangle, the square of the hypotenuse equals the sum of the squares of the other two sides.',
            fontSize: 28,
            fontFamily: 'Arial',
            enterTime: 2.5,
            duration: 7.5,
            enterAnim: 'fly_in_bottom',
            exitAnim: 'none',
            enterAnimDur: 0.6,
            exitAnimDur: 0.5,
          },
          {
            id: qed,
            type: 'latex',
            name: 'Q.E.D.',
            x: 960,
            y: 820,
            width: 120,
            height: 80,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 3,
            latex: '\\square',
            enterTime: 7.5,
            duration: 2.5,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
  {
    id: 'algo_steps',
    label: 'Algorithm Steps',
    description: 'Three-step flowchart: Start → Process → End',
    icon: '⚙',
    category: 'programming',
    project: () => {
      const box1 = uid('obj');
      const box2 = uid('obj');
      const box3 = uid('obj');
      const txt1 = uid('obj');
      const txt2 = uid('obj');
      const txt3 = uid('obj');
      const arr1 = uid('obj');
      const arr2 = uid('obj');
      return {
        name: 'Algorithm Steps',
        editorMode: 'visual',
        codeSource: '',
        stage: { ...STAGE },
        assets: [],
        groups: [],
        sceneDuration: 8,
        objects: [
          {
            id: box1,
            type: 'rectangle',
            name: 'Step 1 box',
            x: 320,
            y: 540,
            width: 320,
            height: 120,
            rotation: 0,
            fill: '#1e40af',
            stroke: '#3b82f6',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 0,
            enterTime: 0,
            duration: 7,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
          {
            id: txt1,
            type: 'text',
            name: 'Start',
            x: 320,
            y: 540,
            width: 320,
            height: 120,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 1,
            content: 'Start',
            fontSize: 32,
            fontFamily: 'Arial',
            enterTime: 0.2,
            duration: 6.8,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.3,
            exitAnimDur: 0.5,
          },
          {
            id: arr1,
            type: 'arrow',
            name: 'Arrow 1',
            // centred in the 320 px gap between two boxes
            x: 640,
            y: 540,
            width: 260,
            height: 0,
            rotation: 0,
            fill: '#94a3b8',
            stroke: '#94a3b8',
            strokeWidth: 3,
            opacity: 1,
            zOrder: 2,
            enterTime: 1.0,
            duration: 6,
            enterAnim: 'grow_arrow',
            exitAnim: 'none',
            enterAnimDur: 0.4,
            exitAnimDur: 0.5,
          },
          {
            id: box2,
            type: 'rectangle',
            name: 'Step 2 box',
            x: 960,
            y: 540,
            width: 320,
            height: 120,
            rotation: 0,
            fill: '#1e40af',
            stroke: '#3b82f6',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 3,
            enterTime: 1.5,
            duration: 5.5,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
          {
            id: txt2,
            type: 'text',
            name: 'Process',
            x: 960,
            y: 540,
            width: 320,
            height: 120,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 4,
            content: 'Process',
            fontSize: 32,
            fontFamily: 'Arial',
            enterTime: 1.7,
            duration: 5.3,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.3,
            exitAnimDur: 0.5,
          },
          {
            id: arr2,
            type: 'arrow',
            name: 'Arrow 2',
            // centred in the 320 px gap between two boxes
            x: 1280,
            y: 540,
            width: 260,
            height: 0,
            rotation: 0,
            fill: '#94a3b8',
            stroke: '#94a3b8',
            strokeWidth: 3,
            opacity: 1,
            zOrder: 5,
            enterTime: 2.5,
            duration: 5,
            enterAnim: 'grow_arrow',
            exitAnim: 'none',
            enterAnimDur: 0.4,
            exitAnimDur: 0.5,
          },
          {
            id: box3,
            type: 'rectangle',
            name: 'Step 3 box',
            x: 1600,
            y: 540,
            width: 320,
            height: 120,
            rotation: 0,
            fill: '#166534',
            stroke: '#22c55e',
            strokeWidth: 2,
            opacity: 1,
            zOrder: 6,
            enterTime: 3.0,
            duration: 5,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.5,
            exitAnimDur: 0.5,
          },
          {
            id: txt3,
            type: 'text',
            name: 'End',
            x: 1600,
            y: 540,
            width: 320,
            height: 120,
            rotation: 0,
            fill: '#ffffff',
            stroke: 'transparent',
            strokeWidth: 0,
            opacity: 1,
            zOrder: 7,
            content: 'End',
            fontSize: 32,
            fontFamily: 'Arial',
            enterTime: 3.2,
            duration: 4.8,
            enterAnim: 'fade_in',
            exitAnim: 'none',
            enterAnimDur: 0.3,
            exitAnimDur: 0.5,
          },
        ],
        tracks: [{ id: 'track_1', name: 'Track 1', clips: [] }],
      };
    },
  },
];

export default TEMPLATES;
