<template>
  <section id="interface" class="split-section">
    <div class="split-container">
      <div class="split-header reveal">
        <div class="section-eyebrow">02 — The Hybrid Interface</div>
        <h2 class="section-title">Canvas Meets<br><em>Code</em></h2>
        <p class="split-intro">
          Drag a shape on the left — Python appears on the right. Every property,
          every keyframe, every morph — all rendered as clean, production-ready Manim
          code you own completely.
        </p>
      </div>

      <div class="split-view reveal reveal-delay-1">
        <!-- Canvas Panel -->
        <div class="split-panel">
          <div class="panel-header">
            <div class="panel-dot panel-dot-r"></div>
            <div class="panel-dot panel-dot-y"></div>
            <div class="panel-dot panel-dot-g"></div>
            <span class="panel-title">canvas · scene_01.mme</span>
          </div>
          <div class="canvas-panel-body">
            <div class="canvas-toolbar">
              <div class="canvas-tool active" title="Select">↖</div>
              <div class="canvas-tool" title="Pan">✥</div>
              <div class="canvas-tool" title="Rectangle">▭</div>
              <div class="canvas-tool" title="Circle">○</div>
              <div class="canvas-tool" title="Text">T</div>
              <div class="canvas-tool" title="LaTeX">∑</div>
              <div class="flex-1"></div>
              <div class="panel-meta">2 objects</div>
            </div>
            <div class="canvas-stage">
              <div class="canvas-obj canvas-obj-1">
                <div class="obj-handle tl"></div>
                <div class="obj-handle tr"></div>
                <div class="obj-handle bl"></div>
                <div class="obj-handle br"></div>
              </div>
              <div class="canvas-obj canvas-obj-2"></div>
              <div class="canvas-obj canvas-obj-3"></div>
            </div>
          </div>
        </div>

        <!-- Divider -->
        <div class="split-divider"></div>

        <!-- Code Panel -->
        <div class="split-panel split-panel--code">
          <div class="panel-header">
            <div class="panel-dot panel-dot-r"></div>
            <div class="panel-dot panel-dot-y"></div>
            <div class="panel-dot panel-dot-g"></div>
            <span class="panel-title">
              <span class="live-indicator">
                <span class="live-dot"></span>live
              </span>
              &nbsp;· scene.py
            </span>
          </div>
          <div id="code-display" class="code-panel-body">
            <!-- Code lines injected by JS -->
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { onMounted, onUnmounted } from 'vue'

let intervalId = null

const codeLines = [
  { tokens: [{ t: 'cm', v: '# Auto-generated by Manim Motion Editor' }] },
  { tokens: [{ t: 'kw', v: 'from' }, { t: 'var', v: ' manim ' }, { t: 'kw', v: 'import' }, { t: 'var', v: ' *' }] },
  { tokens: [] },
  { tokens: [{ t: 'kw', v: 'class' }, { t: 'cls', v: ' MainScene' }, { t: 'punct', v: '(' }, { t: 'cls', v: 'Scene' }, { t: 'punct', v: '):' }] },
  { tokens: [{ t: 'kw', v: '  def' }, { t: 'fn', v: ' construct' }, { t: 'punct', v: '(self):' }] },
  { tokens: [] },
  { tokens: [{ t: 'cm', v: '    # Visual Geometry — Rectangle obj' }] },
  { tokens: [{ t: 'var', v: '    rect ' }, { t: 'punct', v: '=' }, { t: 'fn', v: ' Rectangle' }, { t: 'punct', v: '(' }] },
  { tokens: [{ t: 'var', v: '      width' }, { t: 'punct', v: '=' }, { t: 'num', v: '3.5' }, { t: 'punct', v: ',' }, { t: 'var', v: ' height' }, { t: 'punct', v: '=' }, { t: 'num', v: '2.2' }] },
  { tokens: [{ t: 'var', v: '    )' }] },
  { tokens: [{ t: 'var', v: '    rect' }, { t: 'punct', v: '.' }, { t: 'fn', v: 'set_fill' }, { t: 'punct', v: '(' }, { t: 'cls', v: 'BLUE' }, { t: 'punct', v: ', opacity=' }, { t: 'num', v: '0.3' }, { t: 'punct', v: ')' }] },
  { tokens: [] },
  { tokens: [{ t: 'cm', v: '    # LaTeX expression' }] },
  { tokens: [{ t: 'var', v: '    eq ' }, { t: 'punct', v: '=' }, { t: 'fn', v: ' MathTex' }, { t: 'punct', v: '(' }, { t: 'str', v: '"E = mc^{2}"' }, { t: 'punct', v: ')' }] },
  { tokens: [{ t: 'var', v: '    eq' }, { t: 'punct', v: '.' }, { t: 'fn', v: 'next_to' }, { t: 'punct', v: '(rect, ' }, { t: 'cls', v: 'DOWN' }, { t: 'punct', v: ')' }] },
  { tokens: [] },
  { tokens: [{ t: 'cm', v: '    # Cinematic morph sequence' }] },
  { tokens: [{ t: 'var', v: '    circ ' }, { t: 'punct', v: '=' }, { t: 'fn', v: ' Circle' }, { t: 'punct', v: '(radius=' }, { t: 'num', v: '1.4' }, { t: 'punct', v: ')' }] },
  { tokens: [{ t: 'var', v: '    circ' }, { t: 'punct', v: '.' }, { t: 'fn', v: 'set_stroke' }, { t: 'punct', v: '(' }, { t: 'cls', v: 'GREEN' }, { t: 'punct', v: ')' }] },
  { tokens: [] },
  { tokens: [{ t: 'fn', v: '    self' }, { t: 'punct', v: '.' }, { t: 'fn', v: 'play' }, { t: 'punct', v: '(' }, { t: 'fn', v: 'Create' }, { t: 'punct', v: '(rect))' }] },
  { tokens: [{ t: 'fn', v: '    self' }, { t: 'punct', v: '.' }, { t: 'fn', v: 'play' }, { t: 'punct', v: '(' }, { t: 'fn', v: 'Write' }, { t: 'punct', v: '(eq))' }] },
  { tokens: [{ t: 'fn', v: '    self' }, { t: 'punct', v: '.' }, { t: 'fn', v: 'play' }, { t: 'punct', v: '(' }] },
  { tokens: [{ t: 'fn', v: '      Transform' }, { t: 'punct', v: '(rect, circ),' }] },
  { tokens: [{ t: 'var', v: '      run_time' }, { t: 'punct', v: '=' }, { t: 'num', v: '2.0' }] },
  { tokens: [{ t: 'punct', v: '    )' }] },
]

function renderCode() {
  const el = document.getElementById('code-display')
  if (!el) return
  el.innerHTML = ''
  codeLines.forEach((line, i) => {
    const row = document.createElement('div')
    row.className = 'code-line'
    row.style.opacity = '0'
    row.style.animation = `codeType 0.05s ${i * 0.04}s forwards`
    const ln = document.createElement('span')
    ln.className = 'ln'; ln.textContent = String(i + 1).padStart(2, ' ')
    row.appendChild(ln)
    const content = document.createElement('span')
    content.className = 'code-content'
    line.tokens.forEach(tok => {
      const span = document.createElement('span')
      span.className = tok.t ? `code-${tok.t}` : 'code-var'
      span.textContent = tok.v
      content.appendChild(span)
    })
    row.appendChild(content)
    el.appendChild(row)
  })
}

onMounted(() => {
  renderCode()

  // Periodically "retype" a line to simulate live updates
  intervalId = setInterval(() => {
    const lines = document.querySelectorAll('#code-display .code-line')
    if (!lines.length) return
    const idx = 8 + Math.floor(Math.random() * 8)
    if (lines[idx]) {
      lines[idx].style.animation = 'none'
      lines[idx].style.opacity = '0.3'
      setTimeout(() => {
        lines[idx].style.animation = ''
        lines[idx].style.opacity = '1'
        lines[idx].classList.add('code-line-highlight')
        setTimeout(() => { lines[idx].classList.remove('code-line-highlight') }, 600)
      }, 100)
    }
  }, 2200)
})

onUnmounted(() => {
  if (intervalId !== null) clearInterval(intervalId)
})
</script>
